import React, { useState } from 'react';
import { DatabaseTarget, TuningAuditEntry } from '../types/oracle';
import { generateTuningAuditPdf } from '../utils/pdfGenerator';
import {
  Check,
  CheckCircle2,
  Copy,
  Download,
  FileSpreadsheet,
  FileText,
  Filter,
  Printer,
  ShieldCheck,
  SlidersHorizontal,
  X,
} from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  auditLog: TuningAuditEntry[];
  currentDb?: DatabaseTarget;
  onToast?: (message: string) => void;
}

export const TuningAuditPdfModal: React.FC<Props> = ({
  isOpen,
  onClose,
  auditLog,
  currentDb,
  onToast,
}) => {
  const [meetingTitle, setMeetingTitle] = useState('Oracle DBA Weekly Performance & SQL Tuning Review');
  const [leadDba, setLeadDba] = useState('CHOPADE_V (Principal Oracle DBA)');
  const [meetingDate, setMeetingDate] = useState(() => {
    return new Date().toISOString().split('T')[0];
  });
  const [meetingNotes, setMeetingNotes] = useState(
    'All approved tuning actions successfully stabilized CBO execution plans without production downtime. Rollback scripts verified and tested against standby.'
  );
  const [filterStatus, setFilterStatus] = useState<'ALL' | 'SUCCESS' | 'FAILED' | 'ROLLED_BACK'>('ALL');
  const [includeRollbackPlans, setIncludeRollbackPlans] = useState(true);
  const [includeSignatures, setIncludeSignatures] = useState(true);
  const [isExporting, setIsExporting] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);
  const [showConfig, setShowConfig] = useState(false);

  if (!isOpen) return null;

  const filteredLogs = filterStatus === 'ALL'
    ? auditLog
    : auditLog.filter((entry) => entry.status === filterStatus);

  const totalEntries = filteredLogs.length;
  const successCount = filteredLogs.filter(e => e.status === 'SUCCESS').length;
  const avgImprovement = totalEntries > 0
    ? (filteredLogs.reduce((acc, curr) => acc + curr.measuredImprovementPct, 0) / totalEntries).toFixed(1)
    : '0.0';
  const totalExecutionMs = filteredLogs.reduce((acc, curr) => acc + (curr.executionTimeMs || 0), 0);

  const formattedDate = new Date(meetingDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const handleDownloadPdf = () => {
    try {
      setIsExporting(true);
      const doc = generateTuningAuditPdf(auditLog, {
        meetingTitle,
        leadDba,
        meetingDate: formattedDate,
        meetingNotes,
        database: currentDb,
        includeRollbackPlans,
        filterStatus,
      });

      const cleanDbName = currentDb?.name?.replace(/[^a-zA-Z0-9_-]/g, '_') || 'OracleDB';
      const filename = `DBA_Tuning_Audit_Report_${cleanDbName}_${meetingDate}.pdf`;
      doc.save(filename);

      onToast?.(`Downloaded PDF report: ${filename}`);
    } catch (err: any) {
      console.error('Failed to generate PDF:', err);
      alert(`PDF Generation error: ${err?.message || 'Unknown error'}`);
    } finally {
      setIsExporting(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const mdLines = [
      `# ${meetingTitle}`,
      `**Date:** ${formattedDate} | **Lead DBA:** ${leadDba}`,
      `**Target DB:** ${currentDb?.name || 'PROD_RAC01'} (${currentDb?.environment || 'PRODUCTION'})`,
      `**Oracle Version:** ${currentDb?.version || '19c Enterprise Edition'}`,
      '',
      `## Executive Telemetry Summary`,
      `- **Total Operations:** ${totalEntries}`,
      `- **Success Rate:** ${totalEntries > 0 ? Math.round((successCount / totalEntries) * 100) : 100}%`,
      `- **Average Measured Gain:** +${avgImprovement}%`,
      `- **Total Execution Duration:** ${totalExecutionMs} ms`,
      `- **Compliance Status:** Verified (SOX/HIPAA Audit Signed)`,
      '',
      `## DBA Meeting Notes`,
      `> ${meetingNotes}`,
      '',
      `## Audit Trail Log`,
      `| Timestamp | SQL ID | Action | DBA Operator | Gain | Status | Notes |`,
      `|---|---|---|---|---|---|---|`,
      ...filteredLogs.map(
        e => `| ${e.executedAt} | \`${e.sqlId}\` | ${e.actionType} | ${e.executedBy} | +${e.measuredImprovementPct}% | ${e.status} | ${e.notes} |`
      ),
      '',
      `_Generated by Oracle AI DBA Sentinel_`,
    ];

    navigator.clipboard.writeText(mdLines.join('\n'));
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2500);
    onToast?.('Summary report copied to clipboard (Markdown format)');
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/85 backdrop-blur-sm flex justify-center p-2 sm:p-4 md:p-6 print:p-0 print:bg-white">
      <div className="relative w-full max-w-5xl bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl flex flex-col max-h-[92vh] overflow-hidden print:max-h-none print:border-none print:shadow-none print:bg-white print:rounded-none">
        
        {/* Header toolbar (Hidden when printing) */}
        <div className="px-5 py-4 bg-slate-950 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3 print:hidden">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-red-950/80 border border-red-700/60 text-red-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-white tracking-tight">
                  Tuning Audit Summary PDF & Printable Report
                </h3>
                <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded bg-red-900/40 text-red-300 border border-red-800/60">
                  DBA Status Meeting
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Ready-to-print executive dossier with CBO cost reductions, DDL scripts, and compliance sign-offs.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowConfig(!showConfig)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold border transition-all cursor-pointer ${
                showConfig
                  ? 'bg-cyan-950/80 text-cyan-300 border-cyan-700/70 shadow-sm shadow-cyan-950'
                  : 'bg-slate-800/80 text-slate-300 border-slate-700 hover:bg-slate-700'
              }`}
              title="Customize report metadata, notes, and filters"
            >
              <SlidersHorizontal className="w-3.5 h-3.5" />
              <span>Customize Report</span>
            </button>

            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800/80 text-slate-300 border border-slate-700 hover:bg-slate-700 hover:text-white transition-all cursor-pointer"
              title="Copy text summary for Jira / Confluence / Slack"
            >
              {copiedMarkdown ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="text-emerald-400">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Markdown</span>
                </>
              )}
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800/80 text-slate-200 border border-slate-700 hover:bg-slate-700 hover:text-white transition-all cursor-pointer"
              title="Print document or save via Browser Print dialog"
            >
              <Printer className="w-3.5 h-3.5 text-cyan-400" />
              <span>Print / Save</span>
            </button>

            <button
              onClick={handleDownloadPdf}
              disabled={isExporting}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg text-xs font-bold bg-gradient-to-r from-red-700 to-red-600 hover:from-red-600 hover:to-red-500 text-white shadow-lg shadow-red-950/50 border border-red-500/30 transition-all cursor-pointer disabled:opacity-50"
            >
              {isExporting ? (
                <>
                  <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  <span>Generating PDF...</span>
                </>
              ) : (
                <>
                  <Download className="w-3.5 h-3.5" />
                  <span>Download PDF</span>
                </>
              )}
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors ml-1 cursor-pointer"
              title="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Optional Customization Panel (Collapsible) */}
        {showConfig && (
          <div className="p-4 bg-slate-950/90 border-b border-slate-800/80 text-xs grid grid-cols-1 md:grid-cols-3 gap-4 print:hidden animate-in fade-in duration-200">
            <div>
              <label className="block text-[11px] font-semibold text-slate-400 mb-1">
                Meeting Title / Purpose
              </label>
              <input
                type="text"
                value={meetingTitle}
                onChange={(e) => setMeetingTitle(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-slate-200 text-xs focus:outline-none focus:border-cyan-500"
              />
            </div>

            <div>
              <label className="block text-[11px] font-semibold text-slate-400 mb-1">
                Lead DBA / Presenter
              </label>
              <input
                type="text"
                value={leadDba}
                onChange={(e) => setLeadDba(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-slate-200 text-xs focus:outline-none focus:border-cyan-500"
              />
            </div>

            <div>
              <label className="block text-[11px] font-semibold text-slate-400 mb-1">
                Meeting Date
              </label>
              <input
                type="date"
                value={meetingDate}
                onChange={(e) => setMeetingDate(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-slate-200 text-xs focus:outline-none focus:border-cyan-500"
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-[11px] font-semibold text-slate-400 mb-1">
                Executive Notes & CAB Compliance Decisions
              </label>
              <input
                type="text"
                value={meetingNotes}
                onChange={(e) => setMeetingNotes(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-slate-200 text-xs focus:outline-none focus:border-cyan-500"
              />
            </div>

            <div className="flex items-center gap-4 pt-4">
              <label className="flex items-center gap-2 cursor-pointer select-none text-slate-300">
                <input
                  type="checkbox"
                  checked={includeRollbackPlans}
                  onChange={(e) => setIncludeRollbackPlans(e.target.checked)}
                  className="rounded border-slate-700 text-cyan-500 focus:ring-0"
                />
                <span>Include Rollback Scripts</span>
              </label>

              <label className="flex items-center gap-2 cursor-pointer select-none text-slate-300">
                <input
                  type="checkbox"
                  checked={includeSignatures}
                  onChange={(e) => setIncludeSignatures(e.target.checked)}
                  className="rounded border-slate-700 text-cyan-500 focus:ring-0"
                />
                <span>Include Signature Block</span>
              </label>

              <div className="flex items-center gap-1.5 ml-auto">
                <Filter className="w-3 h-3 text-slate-400" />
                <select
                  value={filterStatus}
                  onChange={(e) => setFilterStatus(e.target.value as any)}
                  className="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-slate-200 text-xs focus:outline-none focus:border-cyan-500"
                >
                  <option value="ALL">All Entries ({auditLog.length})</option>
                  <option value="SUCCESS">Success Only</option>
                  <option value="ROLLED_BACK">Rolled Back</option>
                  <option value="FAILED">Failed</option>
                </select>
              </div>
            </div>
          </div>
        )}

        {/* Printable Paper Document Container */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 bg-slate-950/60 print:p-0 print:bg-white print:overflow-visible">
          
          <div
            id="audit-pdf-printable-document"
            className="max-w-4xl mx-auto bg-white text-slate-900 rounded-xl shadow-xl overflow-hidden print:shadow-none print:rounded-none print:w-full font-sans border border-slate-200 print:border-none"
          >
            {/* Top Brand Banner */}
            <div className="bg-slate-900 text-white p-5 border-b-4 border-red-600">
              <div className="flex items-center justify-between">
                <div>
                  <div className="flex items-center gap-2.5">
                    <span className="bg-red-600 text-white text-[10px] font-black px-2 py-0.5 rounded tracking-wider">
                      ORACLE
                    </span>
                    <h1 className="text-lg font-black tracking-tight text-white">
                      AI DBA SENTINEL
                    </h1>
                  </div>
                  <p className="text-xs text-slate-300 font-medium mt-1">
                    AUTONOMOUS PERFORMANCE TUNING AUDIT &amp; EXECUTIVE COMPLIANCE REPORT
                  </p>
                </div>

                <div className="text-right">
                  <span className="inline-block bg-red-700/80 text-white text-[10px] font-bold px-2.5 py-1 rounded">
                    STATUS MEETING DOSSIER
                  </span>
                  <p className="text-[11px] text-slate-300 mt-1 font-mono">
                    Date: <strong>{formattedDate}</strong>
                  </p>
                </div>
              </div>
            </div>

            {/* Document Body */}
            <div className="p-6 space-y-6">

              {/* Meeting Title & DB Context Card */}
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-4">
                <h2 className="text-base font-bold text-slate-900 border-b border-slate-200 pb-2 mb-3">
                  {meetingTitle}
                </h2>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                  <div className="space-y-1">
                    <div className="flex">
                      <span className="w-32 font-bold text-slate-600">Target Database:</span>
                      <span className="font-semibold text-slate-900">
                        {currentDb?.name || 'PROD_RAC01 (PDB_FIN_CORE)'}
                        <span className="ml-1 text-[10px] px-1.5 py-0.2 rounded bg-slate-200 text-slate-700">
                          {currentDb?.environment || 'PRODUCTION'}
                        </span>
                      </span>
                    </div>
                    <div className="flex">
                      <span className="w-32 font-bold text-slate-600">Oracle Release:</span>
                      <span className="text-slate-800">{currentDb?.version || 'Oracle Database 19c Enterprise Edition'}</span>
                    </div>
                    <div className="flex">
                      <span className="w-32 font-bold text-slate-600">Connection Endpoint:</span>
                      <span className="font-mono text-slate-800">
                        {currentDb?.host ? `${currentDb.host}:${currentDb.port || 1521}/${currentDb.serviceName}` : 'rac-node01.corp.internal:1521/fin_core'}
                      </span>
                    </div>
                  </div>

                  <div className="space-y-1">
                    <div className="flex">
                      <span className="w-32 font-bold text-slate-600">Meeting Lead DBA:</span>
                      <span className="font-semibold text-slate-900">{leadDba}</span>
                    </div>
                    <div className="flex">
                      <span className="w-32 font-bold text-slate-600">Audit Scope:</span>
                      <span className="text-slate-800">{filteredLogs.length} verified tuning operations</span>
                    </div>
                    <div className="flex items-center">
                      <span className="w-32 font-bold text-slate-600">Compliance Status:</span>
                      <span className="inline-flex items-center gap-1 font-bold text-emerald-700 text-xs">
                        <ShieldCheck className="w-3.5 h-3.5" />
                        SOX &amp; HIPAA Verified
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Executive Telemetry KPI Cards */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className="bg-slate-50 border border-slate-200 rounded-lg p-3">
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">
                    Total Operations
                  </span>
                  <div className="text-xl font-black text-slate-900 mt-0.5">
                    {totalEntries}
                  </div>
                  <span className="text-[10px] text-slate-500">Logged actions</span>
                </div>

                <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-3">
                  <span className="text-[10px] font-bold text-emerald-700 uppercase tracking-wider block">
                    Success Rate
                  </span>
                  <div className="text-xl font-black text-emerald-700 mt-0.5">
                    {totalEntries > 0 ? `${Math.round((successCount / totalEntries) * 100)}%` : '100%'}
                  </div>
                  <span className="text-[10px] text-emerald-600">{successCount} successful</span>
                </div>

                <div className="bg-cyan-50 border border-cyan-200 rounded-lg p-3">
                  <span className="text-[10px] font-bold text-cyan-800 uppercase tracking-wider block">
                    Avg Improvement
                  </span>
                  <div className="text-xl font-black text-cyan-700 mt-0.5">
                    +{avgImprovement}%
                  </div>
                  <span className="text-[10px] text-cyan-600">CBO Cost / Latency</span>
                </div>

                <div className="bg-slate-50 border border-slate-200 rounded-lg p-3">
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">
                    Total Maintenance Time
                  </span>
                  <div className="text-xl font-black text-slate-900 mt-0.5">
                    {totalExecutionMs} ms
                  </div>
                  <span className="text-[10px] text-slate-500">Online execution</span>
                </div>
              </div>

              {/* Executive Meeting Note Callout */}
              {meetingNotes && (
                <div className="bg-amber-50/70 border-l-4 border-amber-500 p-3 rounded-r-lg text-xs">
                  <strong className="text-amber-950 font-bold block mb-0.5">
                    DBA Meeting Summary &amp; Compliance Notes:
                  </strong>
                  <p className="text-amber-900">{meetingNotes}</p>
                </div>
              )}

              {/* Audit Trail Table */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-700">
                    Logged Performance Tuning Operations (DBA_AUDIT_TRAIL)
                  </h3>
                  <span className="text-[10px] text-slate-500 font-mono">
                    Showing {filteredLogs.length} entries
                  </span>
                </div>

                <div className="border border-slate-200 rounded-lg overflow-hidden">
                  <table className="w-full text-left text-[11px]">
                    <thead className="bg-slate-900 text-white text-[10px] uppercase font-bold tracking-wider">
                      <tr>
                        <th className="py-2 px-2.5">#</th>
                        <th className="py-2 px-2.5">Timestamp</th>
                        <th className="py-2 px-2.5">SQL ID</th>
                        <th className="py-2 px-2.5">Action Type</th>
                        <th className="py-2 px-2.5">DBA Operator</th>
                        <th className="py-2 px-2.5 text-right">Gain</th>
                        <th className="py-2 px-2.5 text-center">Status</th>
                        <th className="py-2 px-2.5">Impact Summary</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-200">
                      {filteredLogs.map((entry, idx) => (
                        <tr key={entry.id} className={idx % 2 === 1 ? 'bg-slate-50' : 'bg-white'}>
                          <td className="py-2 px-2.5 font-bold text-slate-400 text-center">{idx + 1}</td>
                          <td className="py-2 px-2.5 font-mono text-slate-600 whitespace-nowrap">{entry.executedAt}</td>
                          <td className="py-2 px-2.5 font-mono font-bold text-blue-700">{entry.sqlId}</td>
                          <td className="py-2 px-2.5">
                            <span className="px-1.5 py-0.5 rounded text-[9.5px] font-semibold bg-slate-100 text-slate-800 border border-slate-200">
                              {entry.actionType}
                            </span>
                          </td>
                          <td className="py-2 px-2.5 text-slate-800 whitespace-nowrap">{entry.executedBy}</td>
                          <td className="py-2 px-2.5 font-bold text-emerald-700 text-right whitespace-nowrap">
                            +{entry.measuredImprovementPct}%
                          </td>
                          <td className="py-2 px-2.5 text-center whitespace-nowrap">
                            <span
                              className={`inline-flex items-center gap-1 text-[9px] font-bold px-1.5 py-0.5 rounded ${
                                entry.status === 'SUCCESS'
                                  ? 'bg-emerald-100 text-emerald-800'
                                  : entry.status === 'ROLLED_BACK'
                                  ? 'bg-amber-100 text-amber-800'
                                  : 'bg-red-100 text-red-800'
                              }`}
                            >
                              <CheckCircle2 className="w-2.5 h-2.5" />
                              {entry.status}
                            </span>
                          </td>
                          <td className="py-2 px-2.5 text-slate-600 max-w-xs">{entry.notes}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Rollback & DDL Details */}
              {includeRollbackPlans && filteredLogs.length > 0 && (
                <div className="page-break-inside-avoid">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                    Executed DDL Statements &amp; Emergency Rollback Procedures
                  </h3>
                  <div className="border border-slate-200 rounded-lg overflow-hidden">
                    <table className="w-full text-left text-[10.5px]">
                      <thead className="bg-slate-800 text-white text-[10px] uppercase font-bold tracking-wider">
                        <tr>
                          <th className="py-2 px-2.5 w-24">SQL ID</th>
                          <th className="py-2 px-2.5 w-28">Action</th>
                          <th className="py-2 px-2.5">Executed Command / DBMS Script</th>
                          <th className="py-2 px-2.5">Rollback Command</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-200 font-mono">
                        {filteredLogs.map((entry, idx) => (
                          <tr key={entry.id} className={idx % 2 === 1 ? 'bg-slate-50' : 'bg-white'}>
                            <td className="py-2 px-2.5 font-bold text-blue-700">{entry.sqlId}</td>
                            <td className="py-2 px-2.5 font-sans font-medium text-slate-700">{entry.actionType}</td>
                            <td className="py-2 px-2.5 text-slate-800 text-[10px] break-all">
                              {entry.executedCommands.join('; ')}
                            </td>
                            <td className="py-2 px-2.5 text-amber-700 text-[10px] break-all">
                              {entry.rollbackCommand}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {/* Signatures & Approvals Block */}
              {includeSignatures && (
                <div className="border border-slate-200 rounded-lg p-4 bg-slate-50 page-break-inside-avoid">
                  <div className="flex items-center justify-between mb-3">
                    <h4 className="text-xs font-bold uppercase tracking-wider text-slate-800">
                      CAB (Change Advisory Board) &amp; DBA Compliance Sign-off
                    </h4>
                    <span className="text-[10px] text-slate-500 font-medium">
                      Status Meeting Review Signatures
                    </span>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-2">
                    <div className="space-y-1">
                      <div className="text-[10px] text-slate-500 font-semibold uppercase">
                        Lead Database Administrator
                      </div>
                      <div className="border-b border-slate-400 h-6"></div>
                      <div className="text-xs font-bold text-slate-900 pt-1">{leadDba}</div>
                      <div className="text-[10px] text-slate-500">Date: {formattedDate}</div>
                    </div>

                    <div className="space-y-1">
                      <div className="text-[10px] text-slate-500 font-semibold uppercase">
                        SRE / Infrastructure Director
                      </div>
                      <div className="border-b border-slate-400 h-6"></div>
                      <div className="text-xs font-bold text-slate-900 pt-1">PATEL_A (Head of SRE)</div>
                      <div className="text-[10px] text-slate-500">Date: {formattedDate}</div>
                    </div>

                    <div className="space-y-1">
                      <div className="text-[10px] text-slate-500 font-semibold uppercase">
                        Compliance &amp; Security Officer
                      </div>
                      <div className="border-b border-slate-400 h-6"></div>
                      <div className="text-xs font-bold text-emerald-700 pt-1 flex items-center gap-1">
                        <CheckCircle2 className="w-3 h-3" />
                        AUDIT-APPROVED
                      </div>
                      <div className="text-[10px] text-slate-500">Date: {formattedDate}</div>
                    </div>
                  </div>
                </div>
              )}

              {/* Document Footer */}
              <div className="pt-3 border-t border-slate-200 text-center text-[10px] text-slate-400 flex flex-col sm:flex-row items-center justify-between gap-1">
                <span>Oracle AI DBA Sentinel • Status Meeting Performance Audit Dossier • Confidential</span>
                <span>Generated for internal database governance &amp; CAB review</span>
              </div>

            </div>
          </div>

        </div>

      </div>
    </div>
  );
};
